version: '3.9'

services:
  app:
    container_name: tictactoe
    image: tictactoe
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - 80
    networks:
      - nginx_proxy_default

networks:
  nginx_proxy_default:
    external: true
